//FIRE BASE SATHE CONNECT KARVAMNU CHE
//CATEGORY MA BUTTON CLICK THAY ANE COLOR CHANGE THAY EVU KARVANU CHE
//CLASS NO FUNCTION BANAVI NE KEM UPYOG KARI SAKAY
//CATEGORY NI VASTU NI INFORMATION MALE BATHANI KAY INFORMATION LAKHVA TO NO BESAY
//  ALERT DIALOG AUTOMATIC VAY JAAY SE
//Shareprefrence THi User Under AAve Eltele Biji Var Login N Karvu Pade
